name: meta_vrl_long_map
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - medaka=1.3.2
  - minimap2=2.17
  - snpeff=5.0
  - lofreq=2.1.5
  - cutadapt>=3.2
  - bedtools>=2.30.0
  - samtools>=1.11
  - bcftools>=1.10.2
  - pyfaidx>=0.5.9.5
  - seqkit>=0.15.0